services:
  # 1. MQTT Broker (Lớp Messaging)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot_mosquitto
    ports:
      - "1883:1883" # Port chuẩn MQTT
      - "9001:9001" # Port cho WebSockets (nếu React muốn nghe trực tiếp)
    volumes:
      - ./devops/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - iot_network
    restart: unless-stopped