# Cho phép các listener lắng nghe trên mọi địa chỉ IP (0.0.0.0)
listener 1883 0.0.0.0

# Cho phép kết nối qua WebSockets (Hữu ích nếu Frontend React cần)
listener 9001 0.0.0.0
protocol websockets

# Cho phép kết nối không cần user/pass (Dùng cho môi trường Dev)
# Khi lên Production, hãy đổi thành false và cấu hình password_file
allow_anonymous true

# Nơi lưu trữ dữ liệu bền vững
persistence true
persistence_location /mosquitto/data/

# Cấu hình log
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout